'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System

Partial Public Class Root

    ''' <summary>
    ''' Head control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>
    ''' form1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    ''' <summary>
    ''' HeaderPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HeaderPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' LeftAreaMenu control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected LeftAreaMenu As Global.DevExpress.Web.ASPxMenu

    ''' <summary>
    ''' RightAreaMenu control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RightAreaMenu As Global.DevExpress.Web.ASPxMenu

    ''' <summary>
    ''' ApplicationMenu control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ApplicationMenu As Global.DevExpress.Web.ASPxMenu

    ''' <summary>
    ''' LeftPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected LeftPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' LeftPanelContent control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected LeftPanelContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>
    ''' RightPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RightPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' RightPanelContent control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RightPanelContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>
    ''' PageToolbarPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PageToolbarPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' PageToolbar control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PageToolbar As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>
    ''' PageContent control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PageContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    ''' <summary>
    ''' ApplicationMenuDataSource control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ApplicationMenuDataSource As Global.DevExpress.Web.ASPxSiteMapDataSource
End Class