'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property StudentID As System.Guid
    Public Property StudentName As String
    Public Property IDNo As String
    Public Property IDType As Short
    Public Property DOB As Date
    Public Property ContactNo As String
    Public Property Gender As Short

End Class
